language: node_js
sudo: false
node_js:
  - 7
  - 8
  - 9

os:
  - linux
  - osx

cache:
  directories:
    - node_modules

script:
  - yarn test
  - yarn tsc

deploy:
  skip_cleanup: true
  provider: npm
  email: lamo2k123@gmail.com
  api_key: $NPM_API_KEY
  on:
    node: 9
    tags: true
    repo: lamo2k123/bin-reader
